/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author MIGUELCESARPENHAGOME
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        mMenuPedidos = new javax.swing.JMenuItem();
        mMenuClientes = new javax.swing.JMenu();
        menuItemExcluirCliente = new javax.swing.JMenuItem();
        mFuncionarios = new javax.swing.JMenu();
        mRelatorios = new javax.swing.JMenu();
        mRelatorioCliente = new javax.swing.JMenuItem();
        mRelatorioPedidos = new javax.swing.JMenuItem();
        mRelatorioFuncionarios = new javax.swing.JMenuItem();
        mRelatorioMateriais = new javax.swing.JMenuItem();
        mAgenda = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mCadastro.setText("Pedidos");
        new TelaCadastrarPedido().add(mCadastro);
        mCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroActionPerformed(evt);
            }
        });

        mMenuPedidos.setText("Menu Pedidos");
        mMenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuPedidosActionPerformed(evt);
            }
        });
        mCadastro.add(mMenuPedidos);

        jMenuBar1.add(mCadastro);

        mMenuClientes.setText("Clientes");

        menuItemExcluirCliente.setText("Menu Clientes");
        menuItemExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExcluirClienteActionPerformed(evt);
            }
        });
        mMenuClientes.add(menuItemExcluirCliente);

        jMenuBar1.add(mMenuClientes);

        mFuncionarios.setText("Funcionários");
        jMenuBar1.add(mFuncionarios);

        mRelatorios.setText("Relatórios");

        mRelatorioCliente.setText("Cliente");
        mRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRelatorioClienteActionPerformed(evt);
            }
        });
        mRelatorios.add(mRelatorioCliente);

        mRelatorioPedidos.setText("Pedidos");
        mRelatorioPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRelatorioPedidosActionPerformed(evt);
            }
        });
        mRelatorios.add(mRelatorioPedidos);

        mRelatorioFuncionarios.setText("Funcionarios");
        mRelatorios.add(mRelatorioFuncionarios);

        mRelatorioMateriais.setText("Materiais");
        mRelatorios.add(mRelatorioMateriais);

        jMenuBar1.add(mRelatorios);

        mAgenda.setText("Agenda");
        jMenuBar1.add(mAgenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(360, 360, 360)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(757, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroActionPerformed
        new TelaCadastrarPedido();
    }//GEN-LAST:event_mCadastroActionPerformed

    private void mMenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuPedidosActionPerformed
        new TelaMenuPedidos();
    }//GEN-LAST:event_mMenuPedidosActionPerformed

    private void menuItemExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExcluirClienteActionPerformed
        new TelaMenuCliente();
    }//GEN-LAST:event_menuItemExcluirClienteActionPerformed

    private void mRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRelatorioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mRelatorioClienteActionPerformed

    private void mRelatorioPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRelatorioPedidosActionPerformed
        new TelaRelatorioPedidos();
    }//GEN-LAST:event_mRelatorioPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenu mAgenda;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mFuncionarios;
    private javax.swing.JMenu mMenuClientes;
    private javax.swing.JMenuItem mMenuPedidos;
    private javax.swing.JMenuItem mRelatorioCliente;
    private javax.swing.JMenuItem mRelatorioFuncionarios;
    private javax.swing.JMenuItem mRelatorioMateriais;
    private javax.swing.JMenuItem mRelatorioPedidos;
    private javax.swing.JMenu mRelatorios;
    private javax.swing.JMenuItem menuItemExcluirCliente;
    // End of variables declaration//GEN-END:variables
}
